version: "3"

dotenv: ['.env']

vars:
    GOOSE: ./bin/goose -dir "internal/store/migrations" postgres "$POSTGRES_DSN"

tasks:
    build:
      deps: [build-youtupedia, build-goose, style]

    build-youtupedia:
        deps: [sqlc]
        cmds:
            - go build -o bin/youtupedia -ldflags="-s -w" cmd/youtupedia/main.go
        sources:
            - "**/*.go"
            - go.mod
            - go.sum
        generates:
            - bin/youtupedia

    build-goose:
        cmds:
            - go build -o bin/goose -ldflags="-s -w" cmd/goose/main.go
        sources:
            - "cmd/goose/**/*.go"
            - "internal/store/migrations/**/*.go"
            - go.mod
            - go.sum
        generates:
            - bin/goose

    sqlc:
        run: once
        cmds:
            - sqlc generate
        sources:
            - "internal/store/**/*"
        generates:
            - internal/store/queries.sql.go
            - internal/store/db.go
            - internal/store/models.go

    goose:
        deps: [build]
        cmds:
            - "{{.GOOSE}} {{.CLI_ARGS}}"

    migrate:
        deps: [build]
        cmds:
            - "{{.GOOSE}} up"

    style:
      dir: internal/youtupedia
      cmds:
        - npx tailwindcss -i style.css -o static/style.css
      sources:
        - style.css
      generates:
        - static/style.css

    dev:
      deps: [dev-sql, dev-style, dev-go]

    dev-sql:
      cmds:
        - task sqlc -w

    dev-style:
      dir: internal/youtupedia
      cmds:
        - npx tailwindcss -i style.css -o static/style.css -w

    dev-go:
      cmds:
        - gow -e=go,mod,sum,html run cmd/youtupedia/main.go

