-- +goose Up

CREATE TABLE IF NOT EXISTS channels (
    id             VARCHAR(255) NOT NULL PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    videos_list_id VARCHAR(255) NOT NULL,
    thumbnail_url  VARCHAR(255) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS videos (
    id                    VARCHAR(255) NOT NULL PRIMARY KEY,
    channel_id            VARCHAR(255) NOT NULL REFERENCES channels ON DELETE CASCADE ON UPDATE CASCADE,
    published_at          TIMESTAMP NOT NULL,
    title                 VARCHAR(255) NOT NULL,
    description           TEXT NOT NULL,
    thumbnail_url         VARCHAR(255) NOT NULL,
    searchable_transcript TEXT NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS channel_id ON videos(channel_id);

CREATE TABLE IF NOT EXISTS transcripts (
    id       BIGSERIAL PRIMARY KEY,
    video_id VARCHAR(255) NOT NULL REFERENCES videos ON DELETE CASCADE ON UPDATE CASCADE,
    start    DOUBLE PRECISION NOT NULL,
    duration REAL NOT NULL,
    text     TEXT NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS failures (
    id         BIGSERIAL PRIMARY KEY,
    channel_id VARCHAR(255) NOT NULL REFERENCES channels ON DELETE CASCADE ON UPDATE CASCADE,
    data       TEXT NOT NULL, -- Data dependant on type.
    type       VARCHAR(25) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- +goose Down

DROP INDEX IF EXISTS channel_id;

DROP TABLE IF EXISTS failures;

DROP TABLE IF EXISTS transcripts;

DROP TABLE IF EXISTS videos;

DROP TABLE IF EXISTS channels;
