// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package store

import (
	"time"
)

type Channel struct {
	ID           string
	Title        string
	VideosListID string
	ThumbnailUrl string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	CustomUrl    string
}

type Failure struct {
	ID        int64
	ChannelID string
	Data      string
	Type      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Transcript struct {
	ID      int64
	VideoID string
	Start   int32
	Text    string
}

type Video struct {
	ID                   string
	ChannelID            string
	PublishedAt          time.Time
	Title                string
	Description          string
	ThumbnailUrl         string
	SearchableTranscript string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TranscriptType       string
}
